-- SQLite
PRAGMA foreign_keys = ON;

CREATE TABLE User(
  ID TEXT PRIMARY KEY
);

CREATE TABLE Dashboard(
  ID TEXT PRIMARY KEY,
  User_ID TEXT,
  Widgets TEXT,
  FOREIGN KEY (User_ID) REFERENCES User(ID)
);